version: '3'

services:
  portainer:
    image: "${PORTAINER_IMAGE}:${PORTAINER_IMAGE_TAG}"
    container_name: ${PORTAINER_TARGET}
    command: -H unix:///var/run/docker.sock
    restart: always
    security_opt:
      - no-new-privileges:true
    env_file: .env
    networks:
      - ${PORTAINER_NETWORK}
    volumes:
      - "${PORTAINER_AREA}/localtime:/etc/localtime"
      - /var/run/docker.sock:/var/run/docker.sock
      - "${PORTAINER_AREA}/portainer_data:/data"
    ports:
      # -"${PORT_TUNNEL_PORT}:8000"
      - "${PORT_LEGACY_PORT}:9000"
      # - "${PORT_AGENT_PORT}:9001"
      # - "${PORT_SSL_PORT}:9443"

volumes:
  portainer_data:

networks:
  web:
    external: true
    name: ${PORTAINER_NETWORK}

